### ISSUE TITLE
Crash at Download

### ISSUE THREAD

**Issue by RaymondSchnyder** [TsarFox/chandere2#1]
used Command: chandere2 /g/ -d --debug
Logfile: http://pastebin.com/E3nZBqiJ

issue: ValueError: Host could not be detected.

**Comment by TsarFox** [comment]
Thank you for the bug report. Commit d78cf273da16638c7bd8e7fef77301215d64decd should fix this, can you confirm?

**Comment by RaymondSchnyder** [comment]
I can confirm its fixxed now. Thank you very much.
